import type {
  ActivityRecord,
  Category,
  Cohort,
  Community,
  Provider,
  SKU,
  SubCategory,
  User,
} from './types'

const createDate = (iso: string) => new Date(iso)

const providers: Provider[] = [
  {
    id: 'prov-maya',
    name: 'Maya Chen',
    avatar: 'https://i.pravatar.cc/100?img=32',
    headline: 'Ultra-light trek guide & breathwork coach',
    onTimeStartRate: 0.98,
    trusted: true,
    specialties: ['Altitude pacing', 'Mindful hiking', 'Micro-adventure design'],
    bio: 'Maya has led 120+ micro-expeditions across four continents and brings a calm, grounded presence to every cohort.',
    homeBase: 'Kathmandu, Nepal',
  },
  {
    id: 'prov-arjun',
    name: 'Arjun Patel',
    avatar: 'https://i.pravatar.cc/100?img=12',
    headline: 'Functional medicine chef & gut health mentor',
    onTimeStartRate: 0.92,
    trusted: true,
    specialties: ['Fermentation', 'Habit scaffolding', 'Nutrition systems'],
    bio: 'Arjun pairs evidence-backed protocols with joyful food rituals to help you reset sustainably.',
    homeBase: 'Goa, India',
  },
  {
    id: 'prov-lena',
    name: 'Lena Ortiz',
    avatar: 'https://i.pravatar.cc/100?img=5',
    headline: 'Strategic communication coach',
    onTimeStartRate: 0.96,
    trusted: true,
    specialties: ['Executive storytelling', 'Hybrid facilitation', 'Confidence labs'],
    bio: 'Lena works with exec teams across LATAM + US to build influential communicators.',
    homeBase: 'Austin, USA',
  },
  {
    id: 'prov-noah',
    name: 'Noah Williams',
    avatar: 'https://i.pravatar.cc/100?img=22',
    headline: 'Founder-in-residence, Flow Operators',
    onTimeStartRate: 0.89,
    trusted: false,
    specialties: ['Cashflow systems', 'Angel readiness', 'Fractional CFO workflows'],
    bio: 'Noah helps early-stage founders operationalise finance without the overwhelm.',
    homeBase: 'Singapore',
  },
  {
    id: 'prov-elise',
    name: 'Dr. Elise Kang',
    avatar: 'https://i.pravatar.cc/100?img=44',
    headline: 'Neuroscientist & resilience facilitator',
    onTimeStartRate: 0.94,
    trusted: true,
    specialties: ['Stress physiology', 'Executive resilience', 'Neuroleadership'],
    bio: 'Elise designs data-backed training for enterprise teams navigating hyper-growth.',
    homeBase: 'Seoul, South Korea',
  },
  {
    id: 'prov-rivera',
    name: 'Rivera Rapids Collective',
    avatar: 'https://i.pravatar.cc/100?img=16',
    headline: 'Class IV guides with telemetry-backed safety systems',
    onTimeStartRate: 0.95,
    trusted: true,
    specialties: ['Swiftwater rescue', 'Telemetry coaching', 'Adventure logistics'],
    bio: 'Rivera’s crew runs expedition-grade rafting pods with concierge attention to detail.',
    homeBase: 'Rishikesh, India',
  },
  {
    id: 'prov-ami',
    name: 'Ami & Co. Story Studios',
    avatar: 'https://i.pravatar.cc/100?img=28',
    headline: 'Immersive celebration designers & kid-experience directors',
    onTimeStartRate: 0.99,
    trusted: true,
    specialties: ['AR storytelling', 'Family rituals', 'Celebration logistics'],
    bio: 'Ami’s studio crafts beloved IP experiences with community-sourced prop designers.',
    homeBase: 'Tokyo, Japan',
  },
  {
    id: 'prov-nalini',
    name: 'Nalini Rao',
    avatar: 'https://i.pravatar.cc/100?img=18',
    headline: 'Experiential host curating lakeside wellness & celebration escapes',
    onTimeStartRate: 0.97,
    trusted: true,
    specialties: ['Culinary curation', 'Breathwork facilitation', 'Event choreography'],
    bio: 'Nalini blends soulful hosting with operational excellence to stage lakeside magic.',
    homeBase: 'Udaipur, India',
  },
]

const subCategories: SubCategory[] = [
  {
    id: 'sub-nature-wildlife',
    label: 'Nature & Wildlife',
    description: 'Camping circuits and rewilded escapes mapped by our trek leaders.',
    narrative: 'Community-scouted nature immersions that take you from idea to summit.',
    heroImage:
      'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-weekend-trek', 'sku-camping-cave'],
    defaultCommunityId: 'community-trekkers',
  },
  {
    id: 'sub-adventure-rush',
    label: 'Adventure',
    description: 'White-water, cliffside, and adrenaline-forward experiences with concierge safety nets.',
    narrative: 'Dial up your pulse with community-vetted rivers and routes.',
    heroImage:
      'https://images.unsplash.com/photo-1502219422320-9ca47798b23c?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-river-rafting'],
    defaultCommunityId: 'community-rafters',
  },
  {
    id: 'sub-celebration-at-home',
    label: 'Thematic · At-Home',
    description: 'Bring cinematic wonder to your living room with community stylists.',
    narrative: 'Members co-create magical at-home worlds, complete with shoppable blueprints.',
    heroImage:
      'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-doraemon-birthday'],
    defaultCommunityId: 'community-celebrators',
  },
  {
    id: 'sub-celebration-outdoor',
    label: 'Out-of-Home Celebrations',
    description: 'Signature nights under the stars engineered by alumni hosts.',
    narrative: 'Let the community concierge stage your milestone with lakeside magic.',
    heroImage:
      'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-lakeside-celebration'],
    defaultCommunityId: 'community-lakeside',
  },
  {
    id: 'sub-wellness-outdoor',
    label: 'Out-of-Home Wellness',
    description: 'Restorative escapes blending movement, ritual, and nature.',
    narrative: 'Community-crafted resets that swap overwhelm for grounded presence.',
    heroImage:
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-lakeside-wellness'],
    defaultCommunityId: 'community-lakeside',
  },
  {
    id: 'sub-wellness-rituals',
    label: 'Ritual Labs',
    description: 'Chef-led protocols and AI nudges that cement wellness habits.',
    narrative: 'Circle-powered rituals where alumni share playbooks weekly.',
    heroImage:
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-gut-reset'],
    defaultCommunityId: 'community-gut-reset',
  },
  {
    id: 'sub-founder-finance',
    label: 'Founder Finance',
    description: 'Operator-designed systems to command your cashflow.',
    narrative: 'Guild-led dashboards and CFO workflows tested in the field.',
    heroImage:
      'https://images.unsplash.com/photo-1483478550801-7817f0553d5b?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-flow-operators'],
    defaultCommunityId: 'community-wealth-builders',
  },
  {
    id: 'sub-leadership-comms',
    label: 'Leadership Communication',
    description: 'Tell sharper stories across hybrid teams with AI rehearsal loops.',
    narrative: 'Community rehearsal rooms that keep your message on tempo.',
    heroImage:
      'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-communication-studio'],
    defaultCommunityId: 'community-communicators',
  },
  {
    id: 'sub-celebration-lab',
    label: 'Celebration Labs',
    description: 'Design-led masterminds to spin up milestone experiences fast.',
    narrative: 'Tap alumni vendor maps and concierge styling squads in one hub.',
    heroImage:
      'https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=1200&q=80',
    skuIds: ['sku-celebration-lab'],
    defaultCommunityId: 'community-celebrators',
  },
]

const categories: Category[] = [
  {
    id: 'cat-travel',
    label: 'Travel',
    description: 'Action-first adventures with community-led field notes.',
    themeColor: 'teal',
    subCategories: subCategories.filter((sub) => ['sub-nature-wildlife', 'sub-adventure-rush'].includes(sub.id)),
  },
  {
    id: 'cat-experiential-celebration',
    label: 'Experiential Celebration',
    description: 'Communities that co-host unforgettable milestones.',
    themeColor: 'amber',
    subCategories: subCategories.filter((sub) =>
      ['sub-celebration-at-home', 'sub-celebration-outdoor', 'sub-celebration-lab'].includes(sub.id),
    ),
  },
  {
    id: 'cat-health-wellness',
    label: 'Health & Wellness',
    description: 'Collective resets, labs, and retreats built around accountability.',
    themeColor: 'emerald',
    subCategories: subCategories.filter((sub) => ['sub-wellness-outdoor', 'sub-wellness-rituals'].includes(sub.id)),
  },
  {
    id: 'cat-professional-growth',
    label: 'Professional Growth',
    description: 'Operator guilds turning ambition into deliverables right now.',
    themeColor: 'cyan',
    subCategories: subCategories.filter((sub) => ['sub-founder-finance', 'sub-leadership-comms'].includes(sub.id)),
  },
]

const skus: SKU[] = [
  {
    id: 'sku-weekend-trek',
    categoryId: 'cat-travel',
    subCategoryId: 'sub-nature-wildlife',
    theme: 'Weekend Trek',
    tagline: 'Micro-expedition with concierge logistics and pre-training checks.',
    description:
      'Launch into action with a fully-scaffolded Himalayan sunrise trek. Concierge prep, acclimatisation plan, and a private cohort room keep you progressing from day one.',
    heroImage:
      'https://images.unsplash.com/photo-1517821365201-1dc3f75e9a1c?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'multi',
    intensity: 'intermediate',
    upcomingCohortIds: ['cohort-trek-1', 'cohort-trek-2'],
    relatedCommunityIds: ['community-trekkers'],
    addOns: [
      {
        id: 'addon-gear',
        name: 'Performance Gear Kit',
        description: 'Curated essentials shipped to your door before departure.',
        price: 220,
      },
      {
        id: 'addon-recovery',
        name: 'Recovery Lounge Pass',
        description: 'Access to post-trek spa and guided recovery session.',
        price: 140,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-trek-1',
        title: 'Sunrise Summit Circle',
        description: '12 alumni celebrating their pre-dawn summit ritual together.',
        image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'How fit do I need to be?',
        answer: 'Able to comfortably jog 5km. Maya’s pacing and acclimatisation makes it achievable.',
        answeredBy: 'Maya Chen',
      },
      {
        question: 'What if the weather shifts?',
        answer: 'We confirm forecasts 72 hours prior. Backup sunrise ridge ensures experience even if peaks close.',
        answeredBy: 'Operations Team',
      },
    ],
    bundleTargets: ['sku-gut-reset', 'sku-camping-cave'],
    variants: [
      {
        id: 'variant-weekend-trek-signature',
        skuId: 'sku-weekend-trek',
        name: 'Signature Sunrise Trek',
        description: '3-day Himalayan ridge with concierge acclimatisation and sunrise summit circle.',
        heroImage:
          'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'offline',
        format: 'group',
        sessionType: 'multi',
        highlights: ['Acclimatisation concierge', 'Summit sunrise circle'],
        upcomingCohortIds: ['cohort-trek-1', 'cohort-trek-2'],
      },
    ],
  },
  {
    id: 'sku-camping-cave',
    categoryId: 'cat-travel',
    subCategoryId: 'sub-nature-wildlife',
    theme: 'Camping & Cave Expedition',
    tagline: 'Starlit bivouacs, limestone caverns, and survival skills in one weekend.',
    description:
      'Guided by local naturalists, this expedition blends forest-base camping with subterranean exploration and leave-no-trace rituals sourced from the Weekend Trekkers community.',
    heroImage:
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'multi',
    intensity: 'intermediate',
    upcomingCohortIds: ['cohort-camping-1'],
    relatedCommunityIds: ['community-trekkers'],
    addOns: [
      {
        id: 'addon-speleology',
        name: 'Speleology Toolkit',
        description: 'Headlamps, safety rig, and geology pocket guide curated by guides.',
        price: 180,
      },
      {
        id: 'addon-camp-chef',
        name: 'Camp Chef Upgrade',
        description: 'Alumni chef joins to craft nutrient-dense camp meals.',
        price: 160,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-cave-1',
        title: 'Glowworm Chamber Circle',
        description: 'Members recorded reflections under a bioluminescent ceiling.',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'Do I need previous caving experience?',
        answer: 'No. Guides run a safety primer and small-team practice before entering the caves.',
        answeredBy: 'Guide Collective',
      },
    ],
    bundleTargets: ['sku-weekend-trek', 'sku-lakeside-wellness'],
    variants: [
      {
        id: 'variant-camping-signature',
        skuId: 'sku-camping-cave',
        name: 'Forest & Cavern Signature',
        description: 'Trail-to-cavern loop with alumni campfire storytelling.',
        heroImage:
          'https://images.unsplash.com/photo-1493815793585-d94ccbc86df8?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'offline',
        format: 'group',
        sessionType: 'multi',
        highlights: ['Night navigation drills', 'Speleology masterclass'],
        upcomingCohortIds: ['cohort-camping-1'],
      },
    ],
  },
  {
    id: 'sku-river-rafting',
    categoryId: 'cat-travel',
    subCategoryId: 'sub-adventure-rush',
    theme: 'River Rafting Surge',
    tagline: 'AI-calibrated rafting pods with pro safety crew and live telemetry.',
    description:
      'Tap into the Adventure collective’s real-time river intel. Choose your stretch, get matched with a raft pod, and enjoy concierge logistics from bus pickup to recovery lounge.',
    heroImage:
      'https://images.unsplash.com/photo-1502219422320-9ca47798b23c?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'single',
    intensity: 'intermediate',
    upcomingCohortIds: ['cohort-raft-1'],
    relatedCommunityIds: ['community-rafters'],
    addOns: [
      {
        id: 'addon-go-pro',
        name: 'Whitewater Media Crew',
        description: 'On-raft videographer edits and shares highlight reel within 24 hours.',
        price: 210,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-raft-1',
        title: 'Class IV Surge Replay',
        description: 'Members broke down paddle calls with slow-motion footage.',
        image: 'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'Is there a fitness screening?',
        answer: 'Yes. AI concierge reviews your self-assessment and assigns pod roles accordingly.',
        answeredBy: 'Adventure Concierge',
      },
    ],
    bundleTargets: ['sku-lakeside-celebration', 'sku-weekend-trek'],
    variants: [
      {
        id: 'variant-rafting-surge',
        skuId: 'sku-river-rafting',
        name: 'Surge Pod',
        description: 'High-flow stretch with elite guides and telemetry coaching.',
        heroImage:
          'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'offline',
        format: 'group',
        sessionType: 'single',
        highlights: ['Telemetry paddle coaching', 'Post-ride recovery lounge'],
        upcomingCohortIds: ['cohort-raft-1'],
      },
    ],
  },
  {
    id: 'sku-gut-reset',
    categoryId: 'cat-health-wellness',
    subCategoryId: 'sub-wellness-rituals',
    theme: 'Gut Reset Sprint',
    tagline: 'Chef-led protocols, live labs, and AI habit nudges.',
    description:
      'Sprint through a joyful 6-week rebuild of your gut health with community accountability, live cook-alongs, and automated check-ins that keep you on track.',
    heroImage:
      'https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'multi',
    intensity: 'introductory',
    upcomingCohortIds: ['cohort-gut-1', 'cohort-gut-2'],
    relatedCommunityIds: ['community-gut-reset'],
    addOns: [
      {
        id: 'addon-labkit',
        name: 'Microbiome Lab Kit',
        description: 'Home testing with personalised read-out session.',
        price: 180,
      },
      {
        id: 'addon-coaching',
        name: '1:1 Habit Calibration',
        description: '30-minute personalised plan with Arjun.',
        price: 95,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-gut-1',
        title: 'Sunday Fermentation Crew',
        description: 'Members traded kimchi recipes + progress photos in week 2.',
        image: 'https://images.unsplash.com/photo-1514516430032-7f40ed986ca9?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'Is it vegetarian friendly?',
        answer: 'Yes. Plant-based playbooks with optional adaptogens ship in the welcome kit.',
        answeredBy: 'Arjun Patel',
      },
    ],
    bundleTargets: ['sku-weekend-trek', 'sku-lakeside-wellness'],
    variants: [
      {
        id: 'variant-gut-reset-core',
        skuId: 'sku-gut-reset',
        name: 'Core Ritual Cohort',
        description: 'Live cook-alongs with AI nudges and accountability pods.',
        heroImage:
          'https://images.unsplash.com/photo-1456406644174-8ddd4cd52a06?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'mixed',
        format: 'group',
        sessionType: 'multi',
        highlights: ['Weekly cook-alongs', 'Habit nudge AI concierge'],
        upcomingCohortIds: ['cohort-gut-1', 'cohort-gut-2'],
      },
    ],
  },
  {
    id: 'sku-lakeside-wellness',
    categoryId: 'cat-health-wellness',
    subCategoryId: 'sub-wellness-outdoor',
    theme: 'Lakeside Candle-light & Canopy – Reset Edition',
    tagline: 'Twilight breathwork, canopy dining, and alumni-led cold plunges.',
    description:
      'Designed by the Lakeside collective, this retreat blends sensory dining with restorative rituals. Expect guided breathwork, cold plunge rotations, and a community-led reflection circle.',
    heroImage:
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'single',
    intensity: 'introductory',
    upcomingCohortIds: ['cohort-lakeside-wellness-1'],
    relatedCommunityIds: ['community-lakeside'],
    addOns: [
      {
        id: 'addon-soundbath',
        name: 'Sunrise Sound Bath',
        description: 'Private crystal bowl experience before breakfast.',
        price: 120,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-lakeside-wellness-1',
        title: 'Dawn Cold Plunge Circle',
        description: 'Community accountability turned sunrise dips into a ritual.',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'Is equipment provided?',
        answer: 'Yes. Robes, insulated towels, and recovery tonics await you on-site.',
        answeredBy: 'Retreat Concierge',
      },
    ],
    bundleTargets: ['sku-gut-reset', 'sku-weekend-trek'],
    variants: [
      {
        id: 'variant-lakeside-reset',
        skuId: 'sku-lakeside-wellness',
        name: 'Reset Under The Stars',
        description: 'Twilight breathwork, canopy dinner, and cold plunge ritual.',
        heroImage:
          'https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'offline',
        format: 'group',
        sessionType: 'single',
        highlights: ['Guided breathwork', 'Alumni-led cold plunge rotation'],
        upcomingCohortIds: ['cohort-lakeside-wellness-1'],
      },
    ],
  },
  {
    id: 'sku-celebration-lab',
    categoryId: 'cat-experiential-celebration',
    subCategoryId: 'sub-celebration-lab',
    theme: 'Celebration Design Lab',
    tagline: 'Design a milestone celebration in 48 hours with pro stylists.',
    description:
      'Plug into a curated roster of experience designers and stylists to spin up your next celebration. Includes AI concept board + vendor negotiation scripts.',
    heroImage:
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'online',
    format: '1-to-1',
    sessionType: 'single',
    intensity: 'introductory',
    upcomingCohortIds: ['cohort-celebrate-1'],
    relatedCommunityIds: ['community-celebrators'],
    addOns: [
      {
        id: 'addon-stylist',
        name: 'On-site stylist squad',
        description: 'Trusted partners execute your design in-market.',
        price: 420,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-celebrate-1',
        title: 'Pop-up rooftop engagement',
        description: 'Community-sourced vendor list activated in under 24 hours.',
        image: 'https://images.unsplash.com/photo-1455734729978-db1ae4f687fc?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'Can you work in new cities?',
        answer: 'Yes. Our vendor map covers 30+ cities globally with hyper-local partners.',
        answeredBy: 'Celebration Concierge',
      },
    ],
    bundleTargets: ['sku-doraemon-birthday', 'sku-lakeside-celebration'],
    variants: [
      {
        id: 'variant-celebration-core',
        skuId: 'sku-celebration-lab',
        name: 'Concierge Blueprint Sprint',
        description: 'Work directly with stylists to deploy a milestone celebration in 48 hours.',
        heroImage:
          'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'online',
        format: '1-to-1',
        sessionType: 'single',
        highlights: ['AI storyboard delivery', 'Community vendor swaps'],
        upcomingCohortIds: ['cohort-celebrate-1'],
      },
    ],
  },
  {
    id: 'sku-doraemon-birthday',
    categoryId: 'cat-experiential-celebration',
    subCategoryId: 'sub-celebration-at-home',
    theme: 'Doraemon Themed Birthday',
    tagline: 'Transport your home into Nobita’s world with interactive story arcs.',
    description:
      'A family-friendly experience kit with live hosts, AR storylines, and snack partners. The Celebration Architects community keeps your prep on rails with unboxing parties and decor tutorials.',
    heroImage:
      'https://images.unsplash.com/photo-1521543832201-0360f0896f52?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'single',
    intensity: 'introductory',
    upcomingCohortIds: ['cohort-doraemon-1'],
    relatedCommunityIds: ['community-celebrators'],
    addOns: [
      {
        id: 'addon-live-host',
        name: 'Live Character Host',
        description: 'Professional host joins virtually to lead games and story beats.',
        price: 95,
      },
      {
        id: 'addon-merch',
        name: 'Premium Prop Crate',
        description: 'Customisable banners, tableware, and party favors shipped in advance.',
        price: 120,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-doraemon-1',
        title: 'Anywhere Door Entrance',
        description: 'Parents re-created the iconic doorway with templates from the community.',
        image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'Can we customise the storyline?',
        answer: 'Absolutely. Submit favourite characters and the AI host adapts mini games on the fly.',
        answeredBy: 'Celebration Storyteller',
      },
    ],
    bundleTargets: ['sku-celebration-lab', 'sku-lakeside-celebration'],
    variants: [
      {
        id: 'variant-doraemon-story',
        skuId: 'sku-doraemon-birthday',
        name: 'Story Arc Adventure',
        description: 'Live hosts plus AR portals bring Doraemon scenes into your living room.',
        heroImage:
          'https://images.unsplash.com/photo-1520013812730-1b6d0a53485d?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'mixed',
        format: 'group',
        sessionType: 'single',
        highlights: ['Interactive AR mini quests', 'Snack pairing guide'],
        upcomingCohortIds: ['cohort-doraemon-1'],
      },
    ],
  },
  {
    id: 'sku-lakeside-celebration',
    categoryId: 'cat-experiential-celebration',
    subCategoryId: 'sub-celebration-outdoor',
    theme: 'Lakeside Candle-light & Canopy',
    tagline: 'Progress from Pinterest board to lakeside canopy with alumni hosts.',
    description:
      'An immersive celebration evening featuring curated menus, canopy lounges, and a dedicated community host to run surprises. Perfect for anniversaries or intimate proposal dinners.',
    heroImage:
      'https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'single',
    intensity: 'introductory',
    upcomingCohortIds: ['cohort-lakeside-celebrate-1'],
    relatedCommunityIds: ['community-lakeside'],
    addOns: [
      {
        id: 'addon-fireflies',
        name: 'Firefly Lantern Parade',
        description: 'Community performers choreograph a lantern moment over the lake.',
        price: 210,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-lakeside-celebrate-1',
        title: 'Acoustic Serenade',
        description: 'Members booked an alumni musician for a surprise proposal set.',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'What happens if it rains?',
        answer: 'Rain plan includes heated marquee, alternate lighting, and indoor lounge partner.',
        answeredBy: 'Celebration Concierge',
      },
    ],
    bundleTargets: ['sku-doraemon-birthday', 'sku-river-rafting'],
    variants: [
      {
        id: 'variant-lakeside-celebrate',
        skuId: 'sku-lakeside-celebration',
        name: 'Twilight Celebration',
        description: 'Golden-hour dining with canopy lounge and curated performance.',
        heroImage:
          'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'offline',
        format: 'group',
        sessionType: 'single',
        highlights: ['Concierge surprise timeline', 'Community vendor collective'],
        upcomingCohortIds: ['cohort-lakeside-celebrate-1'],
      },
    ],
  },
  {
    id: 'sku-flow-operators',
    categoryId: 'cat-professional-growth',
    subCategoryId: 'sub-founder-finance',
    theme: 'Flow Operators Mastery',
    tagline: 'Finance cockpit for founders in four sprints.',
    description:
      'Operationalise your finance function with guided sprints, automated dashboards, and peer templates from venture-backed operators.',
    heroImage:
      'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'online',
    format: 'group',
    sessionType: 'multi',
    intensity: 'advanced',
    upcomingCohortIds: ['cohort-flow-1', 'cohort-flow-2'],
    relatedCommunityIds: ['community-wealth-builders'],
    addOns: [
      {
        id: 'addon-fractional',
        name: 'Fractional CFO Hotline',
        description: '4 async office hours with Noah’s operator desk.',
        price: 260,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-flow-1',
        title: 'Cash runway dashboard swap',
        description: 'Members shared investor-ready dashboards ahead of board meetings.',
        image: 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'Will templates fit APAC compliance?',
        answer: 'Yes. We ship region-specific tax packs + intros to vetted accountants.',
        answeredBy: 'Noah Williams',
      },
    ],
    bundleTargets: ['sku-communication-studio'],
    variants: [
      {
        id: 'variant-flow-core',
        skuId: 'sku-flow-operators',
        name: 'Operator Core Sprint',
        description: 'Four-sprint sequence with peer dashboard swaps and CFO office hours.',
        heroImage:
          'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'online',
        format: 'group',
        sessionType: 'multi',
        highlights: ['Peer dashboard swaps', 'Fractional CFO hotline'],
        upcomingCohortIds: ['cohort-flow-1', 'cohort-flow-2'],
      },
    ],
  },
  {
    id: 'sku-communication-studio',
    categoryId: 'cat-professional-growth',
    subCategoryId: 'sub-leadership-comms',
    theme: 'Leadership Communication Studio',
    tagline: 'C-suite communication intensive with AI rehearsal loops.',
    description:
      'Prototype high-stakes narratives with Lena’s peer coaching circles, AI-assisted rehearsal loops, and global cohort dialogues.',
    heroImage:
      'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'multi',
    intensity: 'intermediate',
    upcomingCohortIds: ['cohort-comm-1', 'cohort-comm-2'],
    relatedCommunityIds: ['community-communicators'],
    addOns: [
      {
        id: 'addon-ai',
        name: 'AI Rehearsal Coach',
        description: 'Personal AI twin calibrates tone + pacing between sessions.',
        price: 130,
      },
      {
        id: 'addon-studio',
        name: 'Studio Lighting Kit',
        description: 'Ships globally with plug-and-play setup video.',
        price: 90,
      },
    ],
    communityHighlights: [
      {
        id: 'highlight-comm-1',
        title: 'Board meeting rewind',
        description: 'Alumni share clips + receive rapid-fire rewrites before presenting.',
        image: 'https://images.unsplash.com/photo-1525130413817-d45c1d127c42?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    qa: [
      {
        question: 'What time zones do live labs cover?',
        answer: 'We run APAC-friendly and Americas-friendly cohorts in parallel with recordings same-day.',
        answeredBy: 'Program Team',
      },
    ],
    bundleTargets: ['sku-weekend-trek', 'sku-flow-operators'],
    variants: [
      {
        id: 'variant-communication-global',
        skuId: 'sku-communication-studio',
        name: 'Global Leadership Pod',
        description: 'Hybrid sessions with AI rehearsal loops and peer critique rooms.',
        heroImage:
          'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
        deliveryMode: 'mixed',
        format: 'group',
        sessionType: 'multi',
        highlights: ['AI rehearsal loops', 'Peer critique rooms'],
        upcomingCohortIds: ['cohort-comm-1', 'cohort-comm-2'],
      },
    ],
  },
]

const cohorts: Cohort[] = [
  {
    id: 'cohort-trek-1',
    skuId: 'sku-weekend-trek',
    providerId: 'prov-maya',
    startDate: createDate('2025-12-05T02:00:00Z'),
    endDate: createDate('2025-12-07T10:00:00Z'),
    location: 'Nagarkot, Nepal',
    timeZone: 'Asia/Kathmandu',
    price: 890,
    capacity: 12,
    seatsLeft: 3,
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'multi',
    perks: ['Private transfer', 'Acclimatisation kit', 'Sunrise photography'],
    weatherOutlook: 'Crisp mornings, clear skies (8°C)',
  },
  {
    id: 'cohort-trek-2',
    skuId: 'sku-weekend-trek',
    providerId: 'prov-maya',
    startDate: createDate('2026-01-17T02:00:00Z'),
    endDate: createDate('2026-01-19T10:00:00Z'),
    location: 'Ridge Above Pokhara, Nepal',
    timeZone: 'Asia/Kathmandu',
    price: 910,
    capacity: 12,
    seatsLeft: 0,
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'multi',
    perks: ['Heated basecamp tents', 'Pre-trip conditioning plan'],
    weatherOutlook: 'Cool nights, chance of snow (5°C)',
  },
  {
    id: 'cohort-camping-1',
    skuId: 'sku-camping-cave',
    providerId: 'prov-maya',
    startDate: createDate('2026-02-14T04:00:00Z'),
    endDate: createDate('2026-02-16T11:00:00Z'),
    location: 'Chitwan Forest + Siddha Gufa, Nepal',
    timeZone: 'Asia/Kathmandu',
    price: 980,
    capacity: 10,
    seatsLeft: 5,
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'multi',
    perks: ['Night navigation drills', 'Glowworm chamber ceremony'],
    weatherOutlook: 'Pleasant evenings, mild humidity (18°C)',
  },
  {
    id: 'cohort-raft-1',
    skuId: 'sku-river-rafting',
    providerId: 'prov-rivera',
    startDate: createDate('2025-12-13T06:30:00Z'),
    endDate: createDate('2025-12-13T12:00:00Z'),
    location: 'Ganges Rapids, Rishikesh, India',
    timeZone: 'Asia/Kolkata',
    price: 420,
    capacity: 14,
    seatsLeft: 7,
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'single',
    perks: ['Telemetry paddle feedback', 'Post-run recovery lounge'],
    weatherOutlook: 'Sunny with mild spray (22°C)',
  },
  {
    id: 'cohort-gut-1',
    skuId: 'sku-gut-reset',
    providerId: 'prov-arjun',
    startDate: createDate('2025-11-22T13:00:00Z'),
    endDate: createDate('2026-01-03T14:00:00Z'),
    location: 'Hybrid · Global Zoom + Retreat pop-ups',
    timeZone: 'Asia/Kolkata',
    price: 540,
    capacity: 40,
    seatsLeft: 8,
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'multi',
    perks: ['Live cook-alongs', 'Nutrition AI check-ins', 'Local sourcing guide'],
  },
  {
    id: 'cohort-gut-2',
    skuId: 'sku-gut-reset',
    providerId: 'prov-arjun',
    startDate: createDate('2026-02-10T13:00:00Z'),
    endDate: createDate('2026-03-23T14:00:00Z'),
    location: 'Hybrid · Global Zoom + Retreat pop-ups',
    timeZone: 'Europe/Amsterdam',
    price: 560,
    capacity: 40,
    seatsLeft: 20,
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'multi',
    perks: ['Seasonal recipes', 'Peer accountability pods'],
  },
  {
    id: 'cohort-celebrate-1',
    skuId: 'sku-celebration-lab',
    providerId: 'prov-maya',
    startDate: createDate('2025-11-18T17:00:00Z'),
    endDate: createDate('2025-11-18T18:30:00Z'),
    location: 'Remote Design Studio',
    timeZone: 'America/Los_Angeles',
    price: 320,
    capacity: 1,
    seatsLeft: 1,
    deliveryMode: 'online',
    format: '1-to-1',
    sessionType: 'single',
    perks: ['AI concept board', 'Supplier roster'],
  },
  {
    id: 'cohort-doraemon-1',
    skuId: 'sku-doraemon-birthday',
    providerId: 'prov-ami',
    startDate: createDate('2025-12-20T08:00:00Z'),
    endDate: createDate('2025-12-20T10:00:00Z'),
    location: 'Hybrid · Live stream from Celebration Studio',
    timeZone: 'Asia/Tokyo',
    price: 210,
    capacity: 25,
    seatsLeft: 9,
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'single',
    perks: ['AR portal access', 'DIY prop workshop'],
  },
  {
    id: 'cohort-lakeside-celebrate-1',
    skuId: 'sku-lakeside-celebration',
    providerId: 'prov-nalini',
    startDate: createDate('2026-02-07T12:30:00Z'),
    endDate: createDate('2026-02-07T17:00:00Z'),
    location: 'Lake Pichola, Udaipur, India',
    timeZone: 'Asia/Kolkata',
    price: 620,
    capacity: 16,
    seatsLeft: 6,
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'single',
    perks: ['Canopy lounge', 'Signature tasting menu', 'Surprise timeline concierge'],
  },
  {
    id: 'cohort-lakeside-wellness-1',
    skuId: 'sku-lakeside-wellness',
    providerId: 'prov-nalini',
    startDate: createDate('2026-02-21T05:30:00Z'),
    endDate: createDate('2026-02-21T11:00:00Z'),
    location: 'Aravalli Foothills, India',
    timeZone: 'Asia/Kolkata',
    price: 480,
    capacity: 18,
    seatsLeft: 12,
    deliveryMode: 'offline',
    format: 'group',
    sessionType: 'single',
    perks: ['Breathwork circle', 'Cold plunge rotation', 'Canopy brunch'],
  },
  {
    id: 'cohort-flow-1',
    skuId: 'sku-flow-operators',
    providerId: 'prov-noah',
    startDate: createDate('2025-12-02T15:00:00Z'),
    endDate: createDate('2026-01-14T16:30:00Z'),
    location: 'Virtual HQ + Singapore immersion',
    timeZone: 'Asia/Singapore',
    price: 740,
    capacity: 25,
    seatsLeft: 5,
    deliveryMode: 'online',
    format: 'group',
    sessionType: 'multi',
    perks: ['Notion finance OS', 'Investor Q&A'],
  },
  {
    id: 'cohort-flow-2',
    skuId: 'sku-flow-operators',
    providerId: 'prov-noah',
    startDate: createDate('2026-02-15T15:00:00Z'),
    endDate: createDate('2026-03-28T16:30:00Z'),
    location: 'Virtual HQ + Singapore immersion',
    timeZone: 'America/New_York',
    price: 720,
    capacity: 25,
    seatsLeft: 17,
    deliveryMode: 'online',
    format: 'group',
    sessionType: 'multi',
    perks: ['Board reporting templates', 'Capital stack simulator'],
  },
  {
    id: 'cohort-comm-1',
    skuId: 'sku-communication-studio',
    providerId: 'prov-lena',
    startDate: createDate('2025-11-25T17:00:00Z'),
    endDate: createDate('2026-01-06T18:30:00Z'),
    location: 'Hybrid: Austin studio + virtual labs',
    timeZone: 'America/Chicago',
    price: 680,
    capacity: 18,
    seatsLeft: 2,
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'multi',
    perks: ['Executive feedback panel', 'AI rehearsal loops'],
  },
  {
    id: 'cohort-comm-2',
    skuId: 'sku-communication-studio',
    providerId: 'prov-lena',
    startDate: createDate('2026-02-04T09:00:00Z'),
    endDate: createDate('2026-03-17T10:30:00Z'),
    location: 'Hybrid: Austin studio + virtual labs',
    timeZone: 'Europe/London',
    price: 720,
    capacity: 18,
    seatsLeft: 12,
    deliveryMode: 'mixed',
    format: 'group',
    sessionType: 'multi',
    perks: ['Executive feedback panel', 'Voice training toolkit'],
  },
]

const communities: Community[] = [
  {
    id: 'community-trekkers',
    name: 'Weekend Trekkers',
    description: 'Micro-adventurers trading altitude tips, gear hacks, and sunrise wins.',
    coverImage:
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    members: 982,
    activeNow: 44,
    relatedSkuIds: ['sku-weekend-trek', 'sku-camping-cave'],
    memberIds: ['user-ava', 'user-luis'],
    feed: [
      {
        id: 'post-trek-1',
        author: 'Priya S.',
        authorType: 'member',
        avatar: 'https://i.pravatar.cc/100?img=48',
        createdAt: createDate('2025-11-12T03:45:00Z'),
        content: 'Back from the Nagarkot cohort! Sharing our sunrise playlist + packing tweaks that saved our knees.',
        media: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80'],
      },
    ],
    upcomingEvents: [
      {
        id: 'event-trekkers-camping',
        title: 'Camping & Cave Expedition Warm-up',
        description: 'Prep circle for February’s expedition—map gear, share training logs, and meet your pod.',
        startsAt: createDate('2026-02-05T14:00:00Z'),
        timeZone: 'Asia/Kathmandu',
        location: 'Campfire Prep Circle · Online',
        host: 'Maya Chen',
        relatedSkuId: 'sku-camping-cave',
        image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'online',
      },
      {
        id: 'event-trekkers-weather',
        title: 'Live: Ridge Weather Watch',
        description: 'AI trail scout + Maya drop a weather briefing and gear swaps for this weekend’s trek.',
        startsAt: createDate('2025-11-30T12:00:00Z'),
        timeZone: 'Asia/Kathmandu',
        location: 'Nagarkot Basecamp Broadcast',
        host: 'AI Trail Scout',
        relatedSkuId: 'sku-weekend-trek',
        image: 'https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=1200&q=80',
        status: 'live',
        format: 'group',
        deliveryMode: 'mixed',
      },
    ],
    aiAgentConfig: {
      cadenceMinutes: 0.5,
      tone: 'energizing',
      defaultPrompts: [
        'Who is locking in their sunrise stretch this week? Drop a photo from your training walk.',
        'Weather check: where in the world are you trekking from? Let’s map the climates.',
      ],
    },
  },
  {
    id: 'community-rafters',
    name: 'River Surge Collective',
    description: 'Adrenaline seekers syncing paddle calls, telemetry tips, and river intel.',
    coverImage:
      'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?auto=format&fit=crop&w=1200&q=80',
    members: 540,
    activeNow: 27,
    relatedSkuIds: ['sku-river-rafting'],
    memberIds: ['user-ava', 'user-luis'],
    feed: [
      {
        id: 'post-raft-1',
        author: 'Rivera Rapids Collective',
        authorType: 'provider',
        avatar: 'https://i.pravatar.cc/100?img=16',
        createdAt: createDate('2025-11-11T18:00:00Z'),
        content: 'Sharing telemetry snapshots from last week’s surge pod—practice the cadence before Saturday’s run.',
      },
    ],
    upcomingEvents: [
      {
        id: 'event-rafters-clinic',
        title: 'Whitewater Safety Clinic',
        description: 'Live drill with Rivera on swiftwater rescue essentials and paddle signals.',
        startsAt: createDate('2025-12-10T05:45:00Z'),
        timeZone: 'Asia/Kolkata',
        location: 'Riverbank HQ · Rishikesh',
        host: 'Rivera Rapids Collective',
        relatedSkuId: 'sku-river-rafting',
        image: 'https://images.unsplash.com/photo-1502219422320-9ca47798b23c?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'offline',
      },
      {
        id: 'event-rafters-spotlight',
        title: 'Pod Spotlight: Surge Alpha',
        description: 'Member spotlight with telemetry breakdowns and Q&A on endurance training.',
        startsAt: createDate('2025-12-18T09:00:00Z'),
        timeZone: 'Asia/Kolkata',
        location: 'Community Stage · Online',
        host: 'AI Engagement Agent',
        image: 'https://images.unsplash.com/photo-1526481280695-3c46917f18ec?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'online',
      },
    ],
    aiAgentConfig: {
      cadenceMinutes: 0.75,
      tone: 'energizing',
      defaultPrompts: [
        'What river stretch are you eyeing next? Drop the grade + date so we can form pods.',
        'Telemetry tip swap: share your favourite paddle drill before the weekend.',
      ],
    },
  },
  {
    id: 'community-gut-reset',
    name: 'Gut Reset Circle',
    description: 'Joyful food rituals, fermentation wins, and body-metric check-ins.',
    coverImage:
      'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80',
    members: 1180,
    activeNow: 58,
    relatedSkuIds: ['sku-gut-reset', 'sku-lakeside-wellness'],
    memberIds: ['user-ava', 'user-jo'],
    feed: [
      {
        id: 'post-gut-1',
        author: 'AI Prep Bot',
        authorType: 'ai-agent',
        avatar: 'https://cdn-icons-png.flaticon.com/512/4712/4712035.png',
        createdAt: createDate('2025-11-12T05:45:00Z'),
        content: 'Poll: What’s your biggest win from week 2? Energy, digestion, sleep, or mood?',
        poll: {
          prompt: 'Week 2 wins check-in',
          options: [
            { id: 'energy', label: 'Energy is up', votes: 48 },
            { id: 'digestion', label: 'Digestion reset', votes: 36 },
            { id: 'sleep', label: 'Sleeping deeper', votes: 27 },
            { id: 'mood', label: 'Mood stability', votes: 21 },
          ],
        },
      },
    ],
    upcomingEvents: [
      {
        id: 'event-gut-potluck',
        title: 'Fermentation Potluck Show-and-Tell',
        description: 'Bring your week-three ferments and swap quick-fire tasting notes.',
        startsAt: createDate('2025-12-01T13:00:00Z'),
        timeZone: 'Asia/Kolkata',
        location: 'Virtual Kitchen Studio',
        host: 'Arjun Patel',
        relatedSkuId: 'sku-gut-reset',
        image: 'https://images.unsplash.com/photo-1514516430032-7f40ed986ca9?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'online',
      },
      {
        id: 'event-gut-lakeside',
        title: 'Candle-light Reset Meetup',
        description: 'Preview the Lakeside canopy ritual with alumni-led breathwork.',
        startsAt: createDate('2026-02-15T04:30:00Z'),
        timeZone: 'Asia/Kolkata',
        location: 'Aravalli Foothills · Retreat Deck',
        host: 'Nalini Rao',
        relatedSkuId: 'sku-lakeside-wellness',
        image: 'https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'offline',
      },
    ],
    aiAgentConfig: {
      cadenceMinutes: 0.75,
      tone: 'warm',
      defaultPrompts: [
        'Drop a photo of tonight’s gut-friendly dinner—we’ll compile a community zine.',
        'Who wants a shout-out in tomorrow’s habit ladder spotlight? Reply with your win.',
      ],
    },
  },
  {
    id: 'community-lakeside',
    name: 'Lakeside Circle',
    description: 'Hosts and seekers co-designing canopy celebrations and restorative escapes.',
    coverImage:
      'https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1200&q=80',
    members: 420,
    activeNow: 23,
    relatedSkuIds: ['sku-lakeside-celebration', 'sku-lakeside-wellness'],
    memberIds: ['user-ava'],
    feed: [
      {
        id: 'post-lakeside-1',
        author: 'Nalini Rao',
        authorType: 'provider',
        avatar: 'https://i.pravatar.cc/100?img=18',
        createdAt: createDate('2025-11-09T20:45:00Z'),
        content: 'Sneak peek of the new canopy layout—integrating alumni feedback on lighting arcs.',
        media: ['https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=800&q=80'],
      },
    ],
    upcomingEvents: [
      {
        id: 'event-lakeside-menu',
        title: 'Menu Composition Lab',
        description: 'Culinary director walks through the new seasonal tasting menu with pairing ideas.',
        startsAt: createDate('2026-01-18T12:00:00Z'),
        timeZone: 'Asia/Kolkata',
        location: 'Lakeside Culinary Studio',
        host: 'Nalini Rao',
        relatedSkuId: 'sku-lakeside-celebration',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'mixed',
      },
      {
        id: 'event-lakeside-reset',
        title: 'Live Now: Breathwork Under The Canopy',
        description: 'Join the cohort for the opening breathwork ritual—drop-in access for alumni.',
        startsAt: createDate('2026-02-21T05:45:00Z'),
        timeZone: 'Asia/Kolkata',
        location: 'Aravalli Foothills · Canopy Deck',
        host: 'Retreat Guides',
        relatedSkuId: 'sku-lakeside-wellness',
        image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
        status: 'live',
        format: 'group',
        deliveryMode: 'offline',
      },
    ],
    aiAgentConfig: {
      cadenceMinutes: 1.25,
      tone: 'warm',
      defaultPrompts: [
        'Share your canopy playlist—we’ll compile a master mix for upcoming celebrations.',
        'Who wants to host the next alumni spotlight under the stars? Call dibs below.',
      ],
    },
  },
  {
    id: 'community-wealth-builders',
    name: 'Wealth Builders Guild',
    description: 'Operators building modern wealth systems together.',
    coverImage:
      'https://images.unsplash.com/photo-1454165205744-3b78555e5572?auto=format&fit=crop&w=1200&q=80',
    members: 640,
    activeNow: 19,
    relatedSkuIds: ['sku-flow-operators'],
    memberIds: ['user-ava'],
    feed: [
      {
        id: 'post-wealth-1',
        author: 'Noah Williams',
        authorType: 'provider',
        avatar: 'https://i.pravatar.cc/100?img=22',
        createdAt: createDate('2025-11-11T16:10:00Z'),
        content: 'Uploading the investor memo template that helped a member close $1.2M last week—grab it in resources.',
      },
    ],
    upcomingEvents: [
      {
        id: 'event-wealth-dashboard',
        title: 'Dashboard Teardown Lounge',
        description: 'Bring your cash runway dashboard for live critique ahead of board season.',
        startsAt: createDate('2025-12-08T16:00:00Z'),
        timeZone: 'Asia/Singapore',
        location: 'Virtual Guild Room',
        host: 'Noah Williams',
        relatedSkuId: 'sku-flow-operators',
        image: 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'online',
      },
    ],
    aiAgentConfig: {
      cadenceMinutes: 1.2,
      tone: 'energizing',
      defaultPrompts: [
        'Flash audit: drop your cash runway number and we’ll celebrate movement next Friday.',
        'Voting time—who wants a teardown of their ops dashboard on Thursday? Reply with a 📊.',
      ],
    },
  },
  {
    id: 'community-communicators',
    name: 'Communication Studio Alumni',
    description: 'Leaders refining narrative craft with peers + AI loops.',
    coverImage:
      'https://images.unsplash.com/photo-1488998527040-85054a85150e?auto=format&fit=crop&w=1200&q=80',
    members: 410,
    activeNow: 14,
    relatedSkuIds: ['sku-communication-studio'],
    memberIds: ['user-ava'],
    feed: [
      {
        id: 'post-comm-1',
        author: 'Elena T.',
        authorType: 'member',
        avatar: 'https://i.pravatar.cc/100?img=41',
        createdAt: createDate('2025-11-11T09:20:00Z'),
        content: 'Shared a before/after of our Series B narrative—AI loop flagged filler words I hadn’t noticed.',
      },
    ],
    upcomingEvents: [
      {
        id: 'event-comm-studio-live',
        title: 'Live Rehearsal Swap',
        description: 'Drop a 2-minute clip for live rewrite coaching with Lena + AI twin feedback.',
        startsAt: createDate('2025-12-03T18:00:00Z'),
        timeZone: 'America/Chicago',
        location: 'Studio Stage · Hybrid',
        host: 'Lena Ortiz',
        relatedSkuId: 'sku-communication-studio',
        image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'mixed',
      },
    ],
    aiAgentConfig: {
      cadenceMinutes: 1,
      tone: 'celebratory',
      defaultPrompts: [
        'Show us your before/after slide glow-ups! We’ll highlight a hero deck Friday.',
        'Quick-fire poll: Which stakeholder conversation needs the most support this week?',
      ],
    },
  },
  {
    id: 'community-celebrators',
    name: 'Celebration Architects',
    description: 'Design-lovers shipping unforgettable gatherings.',
    coverImage:
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
    members: 352,
    activeNow: 16,
    relatedSkuIds: ['sku-celebration-lab', 'sku-doraemon-birthday', 'sku-lakeside-celebration'],
    memberIds: ['user-ava'],
    feed: [
      {
        id: 'post-celebrate-1',
        author: 'Marcelo R.',
        authorType: 'member',
        avatar: 'https://i.pravatar.cc/100?img=14',
        createdAt: createDate('2025-11-10T21:10:00Z'),
        content: 'Our pop-up dinner series launched! Sharing the vendor checklist that saved the day.',
      },
    ],
    upcomingEvents: [
      {
        id: 'event-celebrate-story',
        title: 'Doraemon Storyboarding Session',
        description: 'Ami’s studio co-creates custom story arcs for the next Doraemon birthday cohort.',
        startsAt: createDate('2025-12-15T07:30:00Z'),
        timeZone: 'Asia/Tokyo',
        location: 'Story Studio · Hybrid',
        host: 'Ami & Co.',
        relatedSkuId: 'sku-doraemon-birthday',
        image: 'https://images.unsplash.com/photo-1521543832201-0360f0896f52?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'mixed',
      },
      {
        id: 'event-celebrate-lakeside',
        title: 'Proposal Run-of-Show Clinic',
        description: 'Community hosts share playbooks for surprise reveals during lakeside canopies.',
        startsAt: createDate('2026-01-28T15:00:00Z'),
        timeZone: 'Asia/Kolkata',
        location: 'Canopy Ops Room',
        host: 'Nalini Rao',
        relatedSkuId: 'sku-lakeside-celebration',
        image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        status: 'upcoming',
        format: 'group',
        deliveryMode: 'online',
      },
    ],
    aiAgentConfig: {
      cadenceMinutes: 1.5,
      tone: 'celebratory',
      defaultPrompts: [
        'Spotlight time: who deserves the confetti canon this week? Tag them below!',
        'Drop your moodboard-in-progress—we’ll remix it live on Thursday.',
      ],
    },
  },
]

const user: User = {
  id: 'user-ava',
  name: 'Ava Laurent',
  avatar: 'https://i.pravatar.cc/100?img=55',
  timeZone: 'Europe/Paris',
  isReturning: true,
  interests: ['trekking', 'longevity', 'leadership'],
  joinedCommunityIds: ['community-trekkers', 'community-gut-reset', 'community-wealth-builders'],
  upcomingActivities: [
    {
      cohortId: 'cohort-trek-1',
      skuId: 'sku-weekend-trek',
      title: 'Weekend Trek: Himalayan Sunrise',
      startDate: createDate('2025-12-05T02:00:00Z'),
      endDate: createDate('2025-12-07T10:00:00Z'),
      status: 'upcoming',
      deliveryMode: 'offline',
      format: 'group',
    },
    {
      cohortId: 'cohort-comm-1',
      skuId: 'sku-communication-studio',
      title: 'Leadership Communication Studio',
      startDate: createDate('2025-11-25T17:00:00Z'),
      endDate: createDate('2026-01-06T18:30:00Z'),
      status: 'upcoming',
      deliveryMode: 'mixed',
      format: 'group',
    },
  ],
  waitlistedActivities: [
    {
      cohortId: 'cohort-trek-2',
      skuId: 'sku-weekend-trek',
      title: 'Weekend Trek: Himalayan Sunrise',
      startDate: createDate('2026-01-17T02:00:00Z'),
      endDate: createDate('2026-01-19T10:00:00Z'),
      status: 'waitlisted',
      deliveryMode: 'offline',
      format: 'group',
    },
  ],
  pastActivities: [
    {
      cohortId: 'cohort-gut-1',
      skuId: 'sku-gut-reset',
      title: 'Gut Reset Sprint',
      startDate: createDate('2025-05-10T13:00:00Z'),
      endDate: createDate('2025-06-20T14:00:00Z'),
      status: 'completed',
      deliveryMode: 'mixed',
      format: 'group',
      certificateUrl: '#',
      gallery: [
        'https://images.unsplash.com/photo-1456406644174-8ddd4cd52a06?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1453838956707-38a7aa3cd62d?auto=format&fit=crop&w=800&q=80',
      ],
    },
  ],
}

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

export const mockApi = {
  async getProviders() {
    await delay(180)
    return providers
  },
  async getCategories() {
    await delay(120)
    return categories
  },
  async getSkus() {
    await delay(120)
    return skus
  },
  async getCohorts() {
    await delay(120)
    return cohorts
  },
  async getCommunities() {
    await delay(140)
    return communities
  },
  async getUserProfile() {
    await delay(160)
    return structuredClone(user) as User
  },
  async holdSeat(cohortId: string) {
    await delay(200)
    const cohort = cohorts.find((c) => c.id === cohortId)
    if (!cohort) throw new Error('Cohort not found')
    if (cohort.seatsLeft <= 0) throw new Error('No seats available')
    cohort.seatsLeft -= 1
    return cohort
  },
  async joinWaitlist(cohortId: string) {
    await delay(120)
    return cohorts.find((c) => c.id === cohortId) ?? null
  },
  async postCommunityMessage(communityId: string, content: string) {
    await delay(90)
    const community = communities.find((c) => c.id === communityId)
    if (!community) throw new Error('Community not found')
    const post = {
      id: `post-${Date.now()}`,
      author: user.name,
      authorType: 'member' as const,
      avatar: user.avatar,
      createdAt: new Date(),
      content,
    }
    community.feed.unshift(post)
    return post
  },
  async refreshActivityRecord(): Promise<ActivityRecord[]> {
    await delay(120)
    return structuredClone(user.upcomingActivities)
  },
}

export const dataIndex = {
  providers,
  categories,
  skus,
  cohorts,
  communities,
  user,
}
